### ISSUE TITLE
Error on new security rules

### ISSUE THREAD

**Issue by nuevoalex** [duaraghav8/solium-plugin-security#30]
If I try to use one of the newer security rules I get an error when running Solium:

`✖ [Fatal error] - An error occurred while linting over /home/alex/Work/augur-core/source/contracts/Augur.sol: An error occured while trying to load rules: Unable to load Plugin "solium-plugin-securtiy"`

This is when I include something like

`"securtiy/else-after-elseif": "error",`

when using solium `1.0.9`

**Comment by duaraghav8** [comment]
@nuevoalex there are 2 problems:
- You misspelled `security` to `securtiy` so solium couldn't find the plugin with that name
- The new rules haven't been pushed into production yet. I added a lot more tests for each of them after the bounty and some were failing (false positives). (@Cisplatin has generously patched most of them)
They'll be released in 7-10 days (is it urgent for you though?)

**Comment by nuevoalex** [comment]
Not urgent! Thanks for catching my typo.
