### ISSUE TITLE
failures in travis: Unable to load Plugin

### ISSUE THREAD

**Issue by elopio** [duaraghav8/solium-plugin-security#31]
Hey @duaraghav8, do you know why travis is failing like this?
```
Error: An error occured while trying to load rules: Unable to load Plugin "solium-plugin-security".
```

https://travis-ci.org/duaraghav8/solium-plugin-security/builds/318629461

**Comment by duaraghav8** [comment]
This plugin (and all other solium plugins) need to be globally available to be tested (`npm link` is run in the root dir of the plugin). I need to figure out a way to inject that command to travis, and then this build error will go away.
You can run the same test suite on local machine (see readme developer setup)
