### ISSUE TITLE
Question concerning rules to enable

### ISSUE THREAD

**Issue by Cycl0pe** [duaraghav8/solium-plugin-security#34]
Hi,

I was wondering how you specify that you want to activate all the security rules (enabled and disabled rules by default) in .soliumrc.json file?

Cycl0pe

**Comment by duaraghav8** [comment]
If I understand correctly, you're looking for a single flag which you could toggle in your configuration to enable/disable all rules, without having to specify them individually. Is that right?

If yes, then currently it is not possible. I thought of enabling all security rules in the [solium-all](https://github.com/duaraghav8/Ethlint/blob/master/config/rulesets/solium-all.js) [ruleset](https://ethlint.readthedocs.io/en/latest/user-guide.html#configuring-the-linter), but that forces enabling all style rules too.

You're welcome to share how you imagine this could work in the configuration? you can add to the discussion on https://github.com/duaraghav8/Ethlint/issues/252

**Comment by Cycl0pe** [comment]
Well, I was looking for a way to enable one or all rules disabled by default but I do not know how to do it in the configuration file.

Cycl0pe

**Comment by duaraghav8** [comment]
To clarify, you cannot to that at the moment. You will have to specify all rules as enabled separately in your soliumrc.
The issue I've pointed you to is for allowing people to give ideas on how this can be improved.

**Comment by Cycl0pe** [comment]
I do understand that but how do you enable one specific rule in .soliumrc.json? I did not find any documentation about it.

Thanks

**Comment by duaraghav8** [comment]
The documentation is under Plugins https://ethlint.readthedocs.io/en/latest/user-guide.html#plugins
eg
```json
{
  "plugins": ["security"],
  "rules": {
    "security/rule-name": "error"
  }
}
```

**Comment by Cycl0pe** [comment]
Thanks for your help. I was missing the keyword "security".
